alias aws-login="aws sso login --sso-session nswhprovider"
alias eindex-sesi="export AWS_PROFILE=eindex-sesi"
alias eindex-gsgw="export AWS_PROFILE=eindex-gsgw"
alias eindex-wsnbm="export AWS_PROFILE=eindex-wsnbm"
alias eindex-dev="aws sso login --profile eindex-dev --no-browser && export AWS_PROFILE=eindex-dev"
alias eir-prod="aws sso login --profile eir-prod --no-browser && export AWS_PROFILE=eir-prod"
alias esb-prod="aws sso login --profile esb-prod --no-browser && export AWS_PROFILE=esb-prod"
alias esb-nonp="aws sso login --profile esb-nonp --no-browser && export AWS_PROFILE=esb-nonp"
alias epr-nonp="aws sso login --profile epr-nonp --no-browser && export AWS_PROFILE=epr-nonp"
alias cris-tool="aws sso login --profile cris-tool --no-browser && export AWS_PROFILE=cris-tool"

